version: "2"
linters:
  enable:
    - gocritic
    - gosec
    - misspell
  settings:
    errcheck:
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - fmt.Fprintf
        - fmt.Sscanf
    gocritic:
      disabled-checks:
        - ifElseChain
      enabled-tags:
        - diagnostic
        - performance
    gosec:
      excludes:
        - G204
        - G306
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 5
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
